# Generated by Django 5.1.6 on 2025-04-14 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', '管理者'), ('member', 'メンバー')], default='member', max_length=50, verbose_name='役割'),
        ),
    ]
